SELECT 
    F.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    COUNT(DISTINCT F.REGION) AS REGION_COUNT
FROM 
    FACT_ORDERS F
JOIN 
    DIM_CUSTOMER C ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY 
    F.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING 
    COUNT(DISTINCT F.REGION) > 1
ORDER BY 
    REGION_COUNT DESC;
