-- Use or create the E_COMMERCE database and schema
CREATE OR REPLACE DATABASE E_COMMERCE;
USE DATABASE E_COMMERCE;

CREATE OR REPLACE SCHEMA E_COMMERCE;
USE SCHEMA E_COMMERCE;

-- DIM_CUSTOMER
CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID STRING PRIMARY KEY,
    CUSTOMER_NAME STRING,
    CUSTOMER_REGION STRING
);

-- DIM_PRODUCT
CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID STRING PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING
);

-- DIM_DATE
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID DATE PRIMARY KEY,
    DAY INT,
    MONTH INT,
    YEAR INT,
    WEEKDAY STRING
);

-- FACT_ORDERS
CREATE OR REPLACE TABLE FACT_ORDERS (
    ORDER_ID STRING PRIMARY KEY,
    ORDER_TIMESTAMP TIMESTAMP,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    DATE_ID DATE,
    PRICE NUMBER(10,2),
    QUANTITY INT,
    TOTAL_AMOUNT NUMBER(12,2),
    REGION STRING,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE(DATE_ID)
);
