SELECT 
    D.YEAR,
    D.MONTH,
    P.CATEGORY,
    C.CUSTOMER_REGION,
    SUM(F.TOTAL_AMOUNT) AS MONTHLY_SALES
FROM 
    FACT_ORDERS F
JOIN 
    DIM_PRODUCT P ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN 
    DIM_CUSTOMER C ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN 
    DIM_DATE D ON F.DATE_ID = D.DATE_ID
GROUP BY 
    D.YEAR, D.MONTH, P.CATEGORY, C.CUSTOMER_REGION
ORDER BY 
    D.YEAR, D.MONTH, P.CATEGORY, C.CUSTOMER_REGION;
