WITH Recent_Orders AS (
    SELECT 
        F.CUSTOMER_ID,
        COUNT(F.ORDER_ID) AS ORDER_COUNT
    FROM 
        FACT_ORDERS F
    JOIN 
        DIM_DATE D ON F.DATE_ID = D.DATE_ID
    WHERE 
        D.DATE_ID >= CURRENT_DATE - INTERVAL '30 DAY'
    GROUP BY 
        F.CUSTOMER_ID
)
SELECT 
    C.CUSTOMER_NAME,
    C.CUSTOMER_REGION,
    R.ORDER_COUNT
FROM 
    Recent_Orders R
JOIN 
    DIM_CUSTOMER C ON R.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY 
    R.ORDER_COUNT DESC
LIMIT 5;
